### ISSUE TITLE
#error Dosen't Work On Windows! 

### ISSUE THREAD

**Issue by MijunElMacho21** [Nachtwind1/Mp4-To-Srt#3]
Tried To Install This Library Called pip install opencv-python But It Says This "File "<stdin>", line 1 pip install opencv-python SyntaxError: invalid syntax" "^^^^^^^" Can You Fix This Issue?

Screenshotted Image Here:
![Screenshot_6](https://github.com/Nachtwind1/Mp4-To-Srt/assets/132280765/b186d47a-f5af-4698-a0e2-e306c06ac787)

**Comment by Nachtwind1** [comment]
Open cmd Not Python, win + r and then Type cmd and Press enter. Now you can
install the librarys and Run my Programm. If you want to Run the Programm
you need to Go to the folder with this command "cd {path to File directory
, where the main.py File is}".

MijunElMacho21 ***@***.***> schrieb am Di., 2. Jan. 2024,
05:18:
