### ISSUE TITLE
how did u make the Bad apple but it's youtube comments video?

### ISSUE THREAD

**Issue by ubongashorts** [Nachtwind1/Mp4-To-Srt#5]
Hey this is really awesome stuff I would love to learn how you made the Bad apple but it's youtube comments video. Would you be able to release that program on github as well?

Thank you!

also do u have discord?

**Comment by ubongashorts** [comment]
Youtube is not letting me upload any .ytt file larger than 8kb does anyone know a way to be able to upload larger files? It would greatly help me!

**Comment by Nachtwind1** [comment]
You can't upload any captions files bigger then 8kb if they are .ytt and no .srt file that are bigger then 4kb. And I also haven't found a way around that.

and my discord is "nachtwind." But I don't have a discord server or something like that

**Comment by ubongashorts** [comment]
> You can't upload any captions files bigger then 8kb if they are .ytt and no .srt file that are bigger then 4kb. And I also haven't found a way around that.
> 
> and my discord is "nachtwind." But I don't have a discord server or something like that

Okay gotcha. I sent u a friend request on discord. Also, would you be able to put up the code for the video bad apple but its youtube comments. I would love to mess around with that. Thank you man!

**Comment by Nachtwind1** [comment]
> > You can't upload any captions files bigger then 8kb if they are .ytt and no .srt file that are bigger then 4kb. And I also haven't found a way around that.
> > and my discord is "nachtwind." But I don't have a discord server or something like that
> 
> Okay gotcha. I sent u a friend request on discord. Also, would you be able to put up the code for the video bad apple but its youtube comments. I would love to mess around with that. Thank you man!

I'm currently not home, but don't actually know if I have the project anymore, I made it my laptop, which broke a little while ago (idk why), I did have an external hard drive, but it's probably saved on my internal one.
And I don't know if I can get the project from it.

Sorry.

**Comment by ubongashorts** [comment]
Aww man. If you are able to could you please try to take a look for it! Also do u think it would be possible to use emojis when making it to make it colored? thanks!! PS: i tried adding u on discord my username is ubonga
